stages:
  - make_assets
  - embed_reveal
  - docusaurus

build_dir: /build
output_type: last
output_dir: /output

make_assets:
  plugin: command
  options:
    command: make
    locations:
      - chapters/template-chapter/template-topic/slides
    args:
      - all

embed_reveal:
  plugin: reveal_embed
  options:
    target: docusaurus
    extension: mdx
    build:
      template-chapter-template-topic: template-chapter-template-topic

docusaurus:
  plugin: docusaurus
  options:
    course_name: Computer Architecture
    sidebar: js
    math: true
    structure:
      - Introduction: chapters/landing-page/README.md
      - Lab0 - Recapitulare:
          - Circuite combinaționale:
              path: chapters/combinational-circuits/intro
              extra:
                - media/
              subsections:
                - Lectura/: reading/
          - Porti logice:
              path: chapters/combinational-circuits/logic-gates
              extra:
                - media/
              subsections:
                - Reading/: reading/
          - Summatoare:
              path: chapters/combinational-circuits/adders
              extra:
                - media/
              subsections:
                - Reading/: reading/
          - Circuite secvențiale:
              path: chapters/sequential-circuits/intro
              extra:
                - media/
              subsections:
                - Lectura/: reading/
          - Bistabil D:
              path: chapters/sequential-circuits/d-flip-flop
              extra:
                - media/
              subsections:
                - Lectura/: reading/
          - Automate finite:
              path: chapters/sequential-circuits/fsms
              extra:
                - media/
              subsections:
                - Lectura/: reading/
      - Lab1 - Verilog:
          - Limbaj Verilog:
              path: chapters/verilog/intro
              extra:
                - media/
              subsections:
                - Lectura/: reading/
          - Descriere structurala:
              path: chapters/verilog/basic
              extra:
                - media/
              subsections:
                - Lectura/: reading/
                - Exercitii/: drills/
      - Lab2 - Verilog:
          - Operatori:
              path: chapters/verilog/operators
              extra:
                - media/
              subsections:
                - Lectura/: reading/
                - Exercitii/: drills/
          - Parametri:
              path: chapters/verilog/parameters
              extra:
                - media/
              subsections:
                - Lectura/: reading/
                - Exercitii/: drills/
          - Testare:
              path: chapters/verilog/testing
              extra:
                - media/
              subsections:
                - Lectura/: reading/
                - Exercitii/: drills/
      - Lab3 - Verilog:
          - Always:
              path: chapters/verilog/always
              extra:
                - media/
              subsections:
                - Lectura/: reading/
                - Exercitii/: drills/
          - Debouncer:
              path: chapters/verilog/debouncer
              extra:
                - media/
              subsections:
                - Lectura/: reading/
      - Lab4 - Verilog:
          - Automate finite:
              path: chapters/verilog/fsms
              extra:
                - media/
              subsections:
                - Lectura/: reading/
          - Memorie:
              path: chapters/verilog/memory
              extra:
                - media/
              subsections:
                - Lectura/: reading/
                - Exercitii/: drills/
    static_assets:
      - template-chapter-template-topic: /build/make_assets/chapters/template-chapter/template-topic/slides/_site
    config_meta:
      title: Computer Architecture
      url: http://localhost/
      baseUrl: /computer-architecture/
      onBrokenLinks: warn
      onBrokenMarkdownLinks: warn
    config_socials:
      Main site: https://curs.upb.ro
      OCW: https://ocw.cs.pub.ro/courses/ac-is
    copyright_string: Comnputer Architecture Team
